/**
 * Local review server for the built artifact. Serves .vercel/output/static and applies the
 * headers Vercel would apply: per-route headers from .vercel/output/config.json (including the
 * CSP generated by Astro) and the global headers from vercel.json. Approximation for local
 * review only — the authoritative check is a protected Vercel preview deployment.
 *
 * Usage: node scripts/serve-output.ts [port]
 */
import { createServer } from 'node:http';
import { existsSync, readFileSync, statSync } from 'node:fs';
import { extname, join, normalize } from 'node:path';

const port = Number(process.argv[2] ?? 4330);
const STATIC = join('.vercel', 'output', 'static');
const config = JSON.parse(readFileSync(join('.vercel', 'output', 'config.json'), 'utf8')) as {
  routes: { src?: string; headers?: Record<string, string>; status?: number; continue?: boolean }[];
};
const vercelJson = JSON.parse(readFileSync('vercel.json', 'utf8')) as {
  headers: { source: string; headers: { key: string; value: string }[] }[];
};

const TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.xml': 'application/xml; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
};

function matches(src: string, path: string): RegExpMatchArray | null {
  try {
    return path.match(new RegExp(src.startsWith('^') ? src : `^${src}$`));
  } catch {
    return null;
  }
}

createServer((req, res) => {
  const url = new URL(req.url ?? '/', `http://localhost:${port}`);
  const path = decodeURIComponent(url.pathname);
  const headers: Record<string, string> = {};

  for (const rule of vercelJson.headers) {
    const re = new RegExp(`^${rule.source.replace('(.*)', '.*')}$`);
    if (re.test(path)) for (const h of rule.headers) headers[h.key] = h.value;
  }

  for (const route of config.routes) {
    if (!route.src) continue;
    const m = matches(route.src, path);
    if (!m) continue;
    if (route.status && route.headers?.['Location']) {
      const location = route.headers['Location'].replace(/\$(\d)/g, (_, i: string) => m[Number(i)] ?? '');
      res.writeHead(route.status, { ...headers, Location: location });
      res.end();
      return;
    }
    if (route.headers) Object.assign(headers, route.headers);
    if (!route.continue && route.headers?.['content-security-policy']) break;
  }

  let file = normalize(join(STATIC, path));
  if (!file.startsWith(normalize(STATIC))) {
    res.writeHead(400).end();
    return;
  }
  if (existsSync(file) && statSync(file).isDirectory()) file = join(file, 'index.html');
  let status = 200;
  if (!existsSync(file)) {
    status = 404;
    file = join(STATIC, '404.html');
    const csp = config.routes.find((r) => r.src === '/404')?.headers?.['content-security-policy'];
    if (csp) headers['content-security-policy'] = csp;
  }
  res.writeHead(status, { ...headers, 'Content-Type': TYPES[extname(file)] ?? 'application/octet-stream' });
  res.end(readFileSync(file));
}).listen(port, () => console.log(`Serving built artifact on http://localhost:${port}`));
